//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWEB01B.Models
{
    using System;
    
    public enum ClasificacionMovie : int
    {
        A = 0,
        A_Plus = 1,
        B = 2,
        C = 3,
        D = 4,
        R = 5
    }
}
