//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWEB01B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaCartelera
    {
        public string Cinema { get; set; }
        public string Pelicula { get; set; }
        public string Hora_Tanda { get; set; }
        public string Genero { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.Guid CineId { get; set; }
        public int PeliculaId { get; set; }
        public int TandaId { get; set; }
        public int GeneroId { get; set; }
    }
}
